# Generated by Django 6.0.7 on 2026-07-08 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PARENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Apoderado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Número de WhatsApp con código de país (+51)', max_length=20, null=True, verbose_name='Nro. WhatsApp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Código QR'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('INSTRUCTOR', 'Instructor'), ('PARENT', 'Padre/Apoderado'), ('STUDENT', 'Alumno')], default='STUDENT', max_length=20, verbose_name='Rol'),
        ),
    ]
