# Generated by Django 6.0.7 on 2026-07-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_user_address_user_birth_date_user_blood_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
