# Generated by Django 6.0.7 on 2026-07-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portal_password',
            field=models.CharField(blank=True, help_text='Contraseña en texto plano para fines administrativos.', max_length=128, null=True, verbose_name='Contraseña del Portal (Visible)'),
        ),
    ]
