# Generated by Django 6.0.7 on 2026-07-08 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_payment_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Concepto')),
                ('default_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Base (S/)')),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos de Pago',
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_paid', '-year', '-month'], 'verbose_name': 'Pensión / Cobro', 'verbose_name_plural': 'Pensiones y Cobros'},
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Ej: F001-0000234', max_length=50, null=True, verbose_name='Nro. de Recibo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.CharField(blank=True, choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2, null=True, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='payment',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.concept', verbose_name='Concepto'),
        ),
    ]
