# Generated by Django 6.0.7 on 2026-07-08 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_concept_alter_payment_options_payment_receipt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de Pago'),
        ),
    ]
