"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-usvzrhwb9wtzxen59$x$$jneal=_j$$1u9jk&i@)s8^&%3!g9@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']

# Configuración de Whitenoise para archivos estáticos en producción
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',

    # Local apps
    'users',
    'academy',
    'attendance',
    'billing',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True
USE_L10N = True

# Project translation catalogs. Provides Spanish (es) translations for
# django-unfold's own strings, which the package ships untranslated.
# Takes precedence over app/Django catalogs, so it only overrides the
# Unfold-specific msgids defined in locale/es/LC_MESSAGES/django.po.
LOCALE_PATHS = [BASE_DIR / 'locale']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

CSRF_TRUSTED_ORIGINS = ['https://*.up.railway.app']

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

from django.templatetags.static import static
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "Dojang Segma",
    "SITE_HEADER": "Dojang Taekwondo Segma",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("icon.svg"),  # Placeholder
        "dark": lambda request: static("icon.svg"),
    },
    "COLORS": {
        "primary": {
            "50": "240 249 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56 189 248",
            "500": "14 165 233",
            "600": "2 132 199",
            "700": "3 105 161",
            "800": "7 89 133",
            "900": "12 74 110",
            "950": "8 47 73",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "General",
                "separator": True,
                "items": [
                    {
                        "title": "Inicio",
                        "icon": "home",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Usuarios",
                        "icon": "manage_accounts",
                        "link": reverse_lazy("admin:users_user_changelist"),
                    },
                    {
                        "title": "Alumnos",
                        "icon": "sports_martial_arts",
                        "link": reverse_lazy("admin:users_student_changelist"),
                    },
                    {
                        "title": "Apoderados",
                        "icon": "family_restroom",
                        "link": reverse_lazy("admin:users_parent_changelist"),
                    },
                ],
            },
            {
                "title": "Academia",
                "separator": True,
                "items": [
                    {"title": "Actividades", "icon": "campaign", "link": reverse_lazy("admin:academy_activity_changelist")},
                    {"title": "Grupos de Alumnos", "icon": "calendar_month", "link": reverse_lazy("admin:academy_section_changelist")},
                    {"title": "Grados", "icon": "military_tech", "link": reverse_lazy("admin:academy_grade_changelist")},
                ]
            },
            {
                "title": "Control de Asistencia",
                "separator": True,
                "items": [
                    {"title": "Registrar Asistencia", "icon": "qr_code_scanner", "link": reverse_lazy("attendance:scan")},
                    {"title": "Asistencias", "icon": "how_to_reg", "link": reverse_lazy("admin:attendance_attendance_changelist")},
                ]
            },
            {
                "title": "Finanzas e Inventario",
                "separator": True,
                "items": [
                    {"title": "Conceptos", "icon": "category", "link": reverse_lazy("admin:billing_concept_changelist")},
                    {"title": "Pensiones y Cobros", "icon": "payments", "link": reverse_lazy("admin:billing_payment_changelist")},
                    {"title": "Productos", "icon": "inventory_2", "link": reverse_lazy("admin:billing_product_changelist")},
                    {"title": "Ventas", "icon": "point_of_sale", "link": reverse_lazy("admin:billing_sale_changelist")},
                ]
            }
        ],
    },
}
