# Generated by Django 6.0.7 on 2026-07-08 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del grado o cinturón', max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del grupo o sección (Ej. Infantiles Martes/Jueves)', max_length=100)),
                ('schedule', models.CharField(help_text='Horario', max_length=200)),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='enrolled_sections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
