# Generated by Django 6.0.7 on 2026-07-08 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Actividad / Aviso', 'verbose_name_plural': 'Actividades / Avisos'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Grado / Cinturón', 'verbose_name_plural': 'Grados / Cinturones'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Sección / Grupo', 'verbose_name_plural': 'Secciones / Grupos'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.TextField(help_text='Detalle de la actividad', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(help_text='Título del anuncio o actividad', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(help_text='Nombre del grado o cinturón', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to=settings.AUTH_USER_MODEL, verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='Nombre del grupo o sección (Ej. Infantiles Martes/Jueves)', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='section',
            name='schedule',
            field=models.CharField(help_text='Ej: Lunes y Miércoles 4:00pm - 5:30pm', max_length=200, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='enrolled_sections', to=settings.AUTH_USER_MODEL, verbose_name='Alumnos'),
        ),
    ]
