# Generated by Django 6.0.7 on 2026-07-08 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_activity_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Grupo de Alumnos', 'verbose_name_plural': 'Grupos de Alumnos'},
        ),
    ]
