# Generated by Django 6.0.7 on 2026-07-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_section_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, help_text='Opcional. Imagen representativa de la actividad', null=True, upload_to='activities/', verbose_name='Imagen'),
        ),
    ]
