# Generated by Django 6.0.7 on 2026-07-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_activity_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AddField(
            model_name='activity',
            name='image_base64',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Imagen Base64'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='Imagen (opcional)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
